### ISSUE TITLE
Debug - Hopefully this helps.. 

### ISSUE THREAD

**Issue by nexusvue** [TurplePurtle/juniper-bot#2]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle juniper@0.0.1~prestart: juniper@0.0.1
6 silly lifecycle juniper@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle juniper@0.0.1~start: juniper@0.0.1
8 verbose lifecycle juniper@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle juniper@0.0.1~start: PATH: /usr/share/npm/bin/node-gyp-bin:/root/InstaBot/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle juniper@0.0.1~start: CWD: /root/InstaBot
11 silly lifecycle juniper@0.0.1~start: Args: [ '-c', 'node main.js' ]
12 silly lifecycle juniper@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle juniper@0.0.1~start: Failed to exec start script
14 verbose stack Error: juniper@0.0.1 start: `node main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid juniper@0.0.1
16 verbose cwd /root/InstaBot
17 error Linux 4.8.0-30-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error juniper@0.0.1 start: `node main.js`
22 error Exit status 1
23 error Failed at the juniper@0.0.1 start script 'node main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the juniper package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs juniper
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls juniper
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by TurplePurtle** [comment]
I know this is pretty late, but I don't get any error like this in my machine, which makes it hard for me to help you. Best thing I can suggest is to try and rewrite from scratch the part of my bot you're interested in (this code is really not that complicated) and see if/when things go wrong.
